Repository forum2k-smit/DSA-OPEN-SOURCE, pull requests merged in 2021-10, with the labels that each got.

#2 Added Contributing.md
  CONTRIBUTING.md
Labels: SMIT, hacktoberfest

#10 Done with Program of LCA and distance between both nodes
  Program for finding LCA in a binary tree and calculating distance between the two nodes given in queries/distance queries.cpp
Labels: SMIT, hacktoberfest

#9 Python Projects and Education.
  Python_Education/Python Class and objects/basic_class_objs.py
  Python_Education/Python Class and objects/basic_inheritance.py
  Python_Education/Python_regex/basic.py
  Python_Education/Python_regex/imp_points.txt
  Python_Projects/rock_paper_scissors.py
Labels: SMIT, hacktoberfest

#15 Linear Search Algorithm in Python
  Linear Search Algorithm/linear_search.py
Labels: hacktoberfest, lang: python

#19 Updated CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: hacktoberfest

#28 Added Contributors List Auto Updating
  .github/scripts/update-github-contributors.py
  .github/workflows/update-contributors.yml
  README.md
Labels: hacktoberfest

#30 Contributors List Redesigned
  .github/scripts/update-github-contributors.py
  README.md
Labels: documentation, hacktoberfest
